Import('RTT_ROOT')
Import('rtconfig')
from building import *

comm = rtconfig.ARCH + '/common'
path = rtconfig.ARCH + '/' + rtconfig.CPU
ASFLAGS = ''
CCFLAGS = ''

# The set of source files associated with this SConscript file.
if rtconfig.PLATFORM == 'armcc':
	src = Glob(path + '/*.c') + Glob(path + '/*_rvds.S') + Glob(comm + '/*.c')

if rtconfig.PLATFORM == 'gcc':
	src = Glob(path + '/*.c') + Glob(path + '/*_gcc.S') + Glob(comm + '/*.c') + Glob(path + '/*_init.S')

	
if rtconfig.PLATFORM == 'armcc' and rtconfig.ARCH == 'arm' and rtconfig.CPU == 'arm926':
    ASFLAGS = ' --cpreproc'
    
if GetDepend('RT_DEBUG_BACKTRACE') == True:
    CCFLAGS = ' -mbacktrace'
    
CPPPATH = [RTT_ROOT + '/libcpu/' + rtconfig.ARCH + '/' + rtconfig.CPU, RTT_ROOT + '/libcpu/' + rtconfig.ARCH + '/common']
group = DefineGroup(rtconfig.CPU, src, depend = [''], CPPPATH = CPPPATH, ASFLAGS = ASFLAGS, CCFLAGS = CCFLAGS)

Return('group')
