.PHONY: clean All

All:
	@echo "----------Building project:[ rt-thread - BuildSet ]----------"
	@make -f  "rt-thread.mk" && make -f  "rt-thread.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ rt-thread - BuildSet ]----------"
	@make -f  "rt-thread.mk" clean
