from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd + '/../include']
group   = DefineGroup('device', src, depend = ['RT_USING_HWTIMER'], CPPPATH = CPPPATH)

Return('group')
