from building import *
Import('rtconfig')

src = Glob('*.c') + Glob('*.cpp')
cwd = GetCurrentDir()
group = []

CPPPATH = [cwd]
CPPDEFINES = []

if rtconfig.PLATFORM == 'gcc' and rtconfig.ARCH == 'c-sky':
    group = DefineGroup('minilibc', src, depend = ['RT_USING_LIBC'],
        CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
