from building import *

cwd     = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd + '/../include']
group = DefineGroup('device', src, depend = ['RT_USING_SERIAL'], CPPPATH = CPPPATH)

Return('group')
