# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('minilibc', src, depend = ['RT_USING_DEVICE', 'RT_USING_LIBC'], CPPPATH = CPPPATH)

Return('group')
